title: "Dan Liu's Website"
author: "Dan Liu"
description: "Western University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "dliu.pdf"}
  #- {title: "About Me", file: "README.md"}
  - {title: "Research", file: "research.md"}
  - {title: "Presentation", file: "present.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:dliu372@uwo.ca"}
  - {title: Github, icon: github, url: "https://github.com/dliustats"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/dliu539/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
